driver:
  name: docker
  chef_bootstrap_url: nil
  use_cache: true
  use_sudo: <% if ENV["TRAVIS"] then true else false end %>
  #kitchen-docker can't parse docker 1.12 build -q output
  #https://github.com/test-kitchen/kitchen-docker/issues/225
  #build_options: "-q"

# Will be filled out in .kitchen.local.yml
platforms: []

# Non-deterministically, gets this error:
# fatal: [ubuntu-xenial-docker] => failed to parse: bash: warning: setlocale:
# LC_ALL: cannot change locale (en_US.UTF-8)
# - name: ubuntu-xenial-docker
#   driver_config:
#     use_cache: true
#     image: ubuntu:16.04

provisioner:
  name: ansible_push
  idempotency_test: true
  playbook: kitchen-playbook.yml
  support_older_version: true
  verbose: <%= ENV["ANSIBLE_VERBOSE"] %>
  extra_vars:
    # We will override this in .kitchen.local.yml so that we can
    # manually run kitchen commands later without having to set this
    # environment variable
    role_under_test: <%= ENV["ROLE_UNDER_TEST"] %>

# Will be filled out in .kitchen.local.yml
suites: []

verifier:
  name: serverspec
  additional_install_command: mkdir -p /tmp/kitchen
  sudo: false
  # Avoid "sudo: gem: command not found"
  sudo_command: "sudo -E"
  # test_serverspec_installed: false
  default_pattern: true
  # false to run serverspec on local machine, true to run remotely
  remote_exec: true
