driver:
  name: docker
  use_sudo: <% if ENV["TRAVIS"] then true else false end %>
  use_cache: true
  devices:
    - /dev/fuse
  #kitchen-docker can't parse docker 1.12 build -q output
  #https://github.com/test-kitchen/kitchen-docker/issues/225
  #build_options: "-q"

# Will be filled out in .kitchen.local.yml
platforms: []

# Non-deterministically, gets this error:
# fatal: [ubuntu-xenial-docker] => failed to parse: bash: warning: setlocale:
# LC_ALL: cannot change locale (en_US.UTF-8)
# - name: ubuntu-xenial-docker
#   driver_config:
#     use_cache: true
#     image: ubuntu:16.04

provisioner:
  name: ansible_push
  idempotency_test: true
  playbook: kitchen-playbook.yml
  support_older_version: true
  verbose: <%= ENV["ANSIBLE_VERBOSE"] %>
  extra_vars:
    # We will override this in .kitchen.local.yml so that we can
    # manually run kitchen commands later without having to set this
    # environment variable
    role_under_test: <%= ENV["ROLE_UNDER_TEST"] %>

# Will be filled out in .kitchen.local.yml
suites: []

#verifier:
# TODO
#  name: serverspec
#  additional_install_command: mkdir -p /tmp/kitchen
#  name: shell
