---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2 on ubuntu 16.04 et al
    sudo: yes
    raw: >
      if command -v apt; then
        test -e /usr/bin/python ||
        (command -v apt && apt -y update && apt install -y python-minimal)
      fi

  - name: install simplejson on CentOS 5 et al
    sudo: yes
    raw: >
      if command -v yum; then
        python -c "import json" ||
        python -c "import simplejson" ||
        (command -v yum && yum -y install python-simplejson)
      fi

  - name: install python-apt on ansible < 1.6.0 and ubuntu et al
    sudo: yes
    raw: >
      if command -v apt-get; then
         python -c "import apt" ||
         (command -v apt-get && apt-get install -y python-apt);
      fi

  - name: install python-pycurl on ansible < 1.6.0 and ubuntu et al
    sudo: yes
    raw: >
      if command -v apt-get; then
         python -c "import pycurl" ||
         (command -v apt-get && apt-get install -y python-pycurl);
      fi

- hosts: all
  roles:
  - "{{role_under_test}}"
