---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2 on ubuntu 16.04 et al
    sudo: yes
    # Needs trailing ";" under certain combinations of docker, ansible
    raw: >
      if command -v apt; then
        test -e /usr/bin/python ||
        (command -v apt && apt -y update && apt install -y python-minimal)
      fi;
    # Needed since Ansible 2.2 per
    # https://github.com/ansible/ansible/pull/17112/files
    changed_when: False

  - name: install simplejson on CentOS 5 et al
    sudo: yes
    # Needs trailing ";" under certain combinations of docker, ansible
    raw: >
      if command -v yum; then
        python -c "import json" ||
        python -c "import simplejson" ||
        (command -v yum && yum -y install python-simplejson)
      fi;
    # Needed since Ansible 2.2 per
    # https://github.com/ansible/ansible/pull/17112/files
    changed_when: False

