---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi

- name: install python-pycurl on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import pycurl" ||
       (command -v apt-get && apt-get install -y python-pycurl);
    fi

# tasks file for fake-role
- name: fake task
  debug: msg="Task completed"

- name: make file
  lineinfile: >
    create=yes dest=/tmp/fakerole.txt state=present line=fakerole
