---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi
  # Needed since Ansible 2.2 per
  # https://github.com/ansible/ansible/pull/17112/files
  changed_when: False
  # sudo doesn't work with raw on ansible 2.3.3.x+ so just skip this
  # task entirely
  when: ansible_version is defined and ansible_version.major < 2
  sudo: yes

- name: install python-pycurl on ansible < 1.6.0 and ubuntu et al
  raw: >
    if command -v apt-get; then
       python -c "import pycurl" ||
       (command -v apt-get && apt-get install -y python-pycurl);
    fi
  # Needed since Ansible 2.2 per
  # https://github.com/ansible/ansible/pull/17112/files
  changed_when: False
  # sudo doesn't work with raw on ansible 2.3.3.x+ so just skip this
  # task entirely
  when: ansible_version is defined and ansible_version.major < 2
  sudo: yes

# tasks file for fake-role-no-tests
- name: fake task
  debug: msg="Task completed"

- name: make file
  lineinfile: >
    create=yes dest=/tmp/fakerole.txt state=present line=fakerole
